### ISSUE TITLE
草泥马-浪费我我2小时-还是找不到为什么

### ISSUE THREAD

**Issue by wyouyou** [JayeWang/dic#12]

**Comment by JayeWang** [comment]
# Apple Mach-O Linker (ld) Error Group

  "tr::TimeRemainder::TimeRemainder(int const&, int const&, int const&, int const&, int const&, int const&, int const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by JayeWang** [comment]
solution: g++ Dic.cpp List.cpp Node.cpp main.cpp io/simpleIo.cpp time/TimeRemainder.cpp -o dic
